language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6

install:
- pip install -r test-requirements.txt

script:
- flake8 connectsdk
