language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6

install:
- pip install -r requirements/test.txt
- pip install -r requirements/sdk.txt

script:
- flake8 connect
- pytest
