language: python


matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.7


install:
- pip install -r test-requirements.txt

script:
- flake8 connectsdk
